balance = 100000000
name = input("请输入您的名字：")
print("姓名正确，请继续输入")
print("-----------------------------")
age = input("请输入您的年龄：")
print("年龄正确，请继续输入")
print("-----------------------------")
identity_card = input("请输入您的身份证号：")
print(f"身份证号正确\n\t欢迎您{name}先生\n\t我们将诚挚欢迎您的到来！\n\t您的余额为：{balance}")
print("-----------------------------")
password = input("请输入您的银行卡密码：")
print("密码正确，请继续输入")
print("-----------------------------")
withdraw = input("请输入您的取款金额：")
print(f"取款成功，您的余额还剩：{balance - int(withdraw)}\n\t欢迎您下次光临，再见！")
